server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.php;
    server_name _;

    merge_slashes off;

    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ @rewrite;
    }

    location @rewrite {
        rewrite ^/(.*)$ /index.php?title=$1&$args last;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_read_timeout 300;
    }

    location ~ /\. {
        deny all;
    }
}
